# Escenario:
Supervisas la producción de chips de silicio. Tienes datos de 5 Máquinas (filas) durante 4 Turnos de trabajo (columnas). 
Los números representan la "Temperatura promedio" de la máquina.

In [2]:
import numpy as np

# Datos de temperatura reportados (lista plana de 20 valores)
# Se supone que son 5 máquinas x 4 turnos
raw_temps = [22.5, 24.1, 28.5, 30.2, 
             21.0, 22.8, 23.5, 24.0, 
             45.2, 48.1, 52.3, 55.8, 
             22.1, 23.4, 25.6, 26.8, 
             19.5, 20.2, 21.5, 22.0]

# Convertimos a array
temps_array = np.array(raw_temps)

Como ya mencionamos al inicio, buscamos separar el array y convertilo en uno no plano como lo tenemos la inicio, sabemso que son 5 maquinas representadas en la fila y 4 columnas que representan los turnos de uso. Usamos el reshape 5,4 para especificar las filas y columnas que queremos formar. 

In [3]:
matrix_chips=temps_array.reshape(5,4)
print(matrix_chips)

[[22.5 24.1 28.5 30.2]
 [21.  22.8 23.5 24. ]
 [45.2 48.1 52.3 55.8]
 [22.1 23.4 25.6 26.8]
 [19.5 20.2 21.5 22. ]]


Como las maquinas son viejas, dan datos innecesarios por lo cual usando el metodo astype modificamos el dato aceptado para obtener unicamente enteros.

In [6]:
matrix_chips=matrix_chips.astype(int)
print(matrix_chips)

[[22 24 28 30]
 [21 22 23 24]
 [45 48 52 55]
 [22 23 25 26]
 [19 20 21 22]]


Como loas temperatura mayores a 40 grados seran considerado peligroso, es por ello que se busca separar y mostrar los que superan los 40 grados usando el filtro tradicional de busqueda en todo el array

In [7]:
mask_peligro=matrix_chips[:]>40
print(matrix_chips[mask_peligro])

[45 48 52 55]


Como quiero obtener los datos de la maquina 3 y 4  durante los turnos  3 y 4. Usamos la extraccion como lo hacemos en las listas y en arrays de dimensiones iniciales.

In [12]:
sub_arr=matrix_chips[2:4,2:4]
print(sub_arr)

[[52 55]
 [25 26]]


Tenemos una nueva maquina, con lso datos mostrados, pues nos pidieron agregarlo al array de las otras maquinas cumpliendo con la forma y dimension que debe tener, es por ello que usamos el concatenate para agregar la neuva maquina al array pricipal.

In [ ]:
maquina_6=np.array([[20,21,22,23]])

matrix_chips=np.concatenate((matrix_chips,maquina_6))
print(matrix_chips)

2
2
[[20 21 22 23]
 [22 24 28 30]
 [21 22 23 24]
 [45 48 52 55]
 [22 23 25 26]
 [19 20 21 22]
 [20 21 22 23]]
