# EJERCICIO N°01 PYTHON : "EL SCOUT DE BASQUETBOL"

In [2]:
import numpy as np

# Datos brutos (una sola lista larga que nos llegó mal del sistema)
# El orden es repetitivo: Altura, Puntos, Edad, Altura, Puntos, Edad...
raw_data = [190, 15, 25, 185, 22, 21, 210, 8, 30, 175, 30, 24, 
            201, 12, 28, 198, 18, 26, 182, 25, 22, 215, 5, 31, 
            192, 14, 23, 188, 20, 25]

# Convertimos a array de numpy
players_array = np.array(raw_data)

Primero ordenamos los datos mediante el uso de reshape para formar las columnas que ya emos definido anteriormente ( altura, puntos y edad )

In [3]:
team_matrix=players_array.reshape(10,3)
print(team_matrix)

[[190  15  25]
 [185  22  21]
 [210   8  30]
 [175  30  24]
 [201  12  28]
 [198  18  26]
 [182  25  22]
 [215   5  31]
 [192  14  23]
 [188  20  25]]


Mediante un loop el cual itera dentro de la matriz por cada fila, usamos una condicional para verificar que el segundo dato de la fila tomada que representa a los puntos del basquetbolista, es mayor a 20 para separarlo y mencionarlo como una estralla, dentro de esta condicion creamos una mascara de True para asi usando el filter imprimir unicamente las filas que cumplen con la condicion, puesta.

In [24]:
"""for fila in team_matrix:
    if fila[1]>20:
        dato=fila>0
        nuevo=np.array(fila[dato])
        print(fila[dato])

LA VERSION ANTERIOR ES UNA VERSION HECHA DE FORMA CLASICA, NO RECOMENDABLE EN DS PUES BUSCAMSO EVITAR BUCLES QUE PUEDEN VOLVERSE MUY PESADOS CON GRANDES CANTIDADES DE DATOS."""

mask=team_matrix[:,1]>20

estrellas=team_matrix[mask]
print(estrellas)

[[185  22  21]
 [175  30  24]
 [182  25  22]]


Mediante un slicing horizontal para separar las columnas le asignamos a 3 variables las 3 columnas separadas, luego creamos una copia de la columna edad y asi poder modificarlo sin necesidad de editar el principal, esto lo guardamos en la variable ages.

In [ ]:
altura,puntos,edad=np.hsplit(team_matrix,3)

ages=np.copy(edad)
print(ages)
#Mi solucion esta bien pero puede causar un poco de molestias si trato de pasar los datos a un modelo de ML pues estos por lo general prefieren datos planos y no de mas dimensiones.
#podria haber hecho el slicing sin necesidad de usar split: ages= team_matrix[:,2].copy

[[25]
 [21]
 [30]
 [24]
 [28]
 [26]
 [22]
 [31]
 [23]
 [25]]


Como tuvimos una equivocacion al momento de asignar una estatura, usando where podemos reemplazar el dato sin necesidad de modificar todos los otros datos o crear un nuevo array.

In [14]:
team_matrix=np.where(team_matrix==215,216,team_matrix)
print(team_matrix)

[[190  15  25]
 [185  22  21]
 [210   8  30]
 [175  30  24]
 [201  12  28]
 [198  18  26]
 [182  25  22]
 [216   5  31]
 [192  14  23]
 [188  20  25]]


In [23]:
train_set,test_set=np.split(team_matrix,[8])
print(train_set)
print(test_set)

[[190  15  25]
 [185  22  21]
 [210   8  30]
 [175  30  24]
 [201  12  28]
 [198  18  26]
 [182  25  22]
 [216   5  31]]
[[192  14  23]
 [188  20  25]]
