#                                                                             **SIMULADOR DE CALL CENTER**

**RETO**: Genera un arreglo que represente las llamadas recibidas por minuto durante una hora (60 minutos) usando una distribución de Poisson con un promedio
 ($\lambda$) de 4 llamadas por minuto.

**Operación Basic**:

Corta el arreglo (Slicing) para ver solo los primeros 15 minutos.

Cambia la forma (Reshape) del arreglo original a una matriz de (6, 10) (donde cada fila es una decena de minutos).

Usa un filtro (Filter) para encontrar en qué minutos se recibieron más de 7 llamadas (posible colapso del sistema).

In [3]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from numpy import random

In [4]:
calls=random.poisson(lam=4,size=60)
print(calls)

[ 4  1  6  3  5  1  4  2  4  3  4  4  8  3  4  5  3  6  3  1 10  4  6  5
  6  2  0  4  1  3  4  3  1  6  3  9  2  7  2  4  3  6  6  3  6  4  3  3
  2  3  4  3  5  6  4  1  5  3  5  6]


In [ ]:
#Mostrar unicamente los 15 primeros numeros
fift=calls[:15] 

#Modificamos la forma del array ahora es de 6 filas y 10 columnas
calls_rs=calls.reshape(6,10)
print(calls_rs)
#Obtenemos los datos cuando sean mayor a 7 usando where
fila,columna=np.where(calls_rs >7)
for i,j in zip(fila,columna):
    print(calls_rs[i,j])


[[ 4  1  6  3  5  1  4  2  4  3]
 [ 4  4  8  3  4  5  3  6  3  1]
 [10  4  6  5  6  2  0  4  1  3]
 [ 4  3  1  6  3  9  2  7  2  4]
 [ 3  6  6  3  6  4  3  3  2  3]
 [ 4  3  5  6  4  1  5  3  5  6]]
8
10
9
